"""initial schema

Revision ID: 523af0ba2cd5
Revises: 
Create Date: 2026-06-02 17:43:55.363990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523af0ba2cd5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('system_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('latest_sync', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type_of_record', sa.String(), nullable=True),
    sa.Column('bibliographic_level', sa.String(), nullable=True),
    sa.Column('latest_transaction', sa.TIMESTAMP(), nullable=True),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_records_search_vector', 'catalog_records', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_catalog_records_updated_at', 'catalog_records', ['updated_at'], unique=False)
    op.create_table('marc_sectors',
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('record_count', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('base', 'sector_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('scope', sa.Enum('Catalog', 'Tasks', 'Validation', 'AuthorityLinking', 'Comparison', 'ProcessRecords', 'Maintenance', name='settingsscope'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scope')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('oidc_sub', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oidc_sub')
    )
    op.create_table('authority_links',
    sa.Column('main_record_id', sa.String(), nullable=False),
    sa.Column('linker', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('authority_record_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['authority_record_id'], ['catalog_records.id'], ),
    sa.ForeignKeyConstraint(['main_record_id'], ['catalog_records.id'], ),
    sa.PrimaryKeyConstraint('main_record_id', 'linker', 'base')
    )
    op.create_table('comparisons',
    sa.Column('main_record_id', sa.String(), nullable=False),
    sa.Column('comparator', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('other_record_id', sa.String(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['main_record_id'], ['catalog_records.id'], ),
    sa.ForeignKeyConstraint(['other_record_id'], ['catalog_records.id'], ),
    sa.PrimaryKeyConstraint('main_record_id', 'comparator', 'base')
    )
    op.create_table('marc_record_index',
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('system_number', sa.String(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('offset_in_sector', sa.Integer(), nullable=False),
    sa.Column('record_length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base', 'sector_id'], ['marc_sectors.base', 'marc_sectors.sector_id'], ),
    sa.PrimaryKeyConstraint('base', 'system_number')
    )
    op.create_index('ix_marc_record_index_sector', 'marc_record_index', ['base', 'sector_id'], unique=False)
    op.create_table('record_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('aspect_name', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['catalog_records.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_record_reviews_lookup', 'record_reviews', ['record_id', 'aspect_name', 'status'], unique=False)
    op.create_table('result_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('aspect_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['catalog_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_result_snapshots_lookup', 'result_snapshots', ['record_id', 'aspect_name'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('FetchRecord', 'FetchBatchOfRecords', 'SyncRecords', 'ValidateRecords', 'LinkRecordsToAuthorities', 'CompareRecords', 'ProcessRecords', 'DeleteTasks', 'RefreshAnalytics', 'CleanupStaleLocks', 'CompactSectors', 'RebuildSearchVectors', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Started', 'Success', 'Failure', 'Revoked', name='taskstatus'), nullable=False),
    sa.Column('severity', sa.Enum('Info', 'Warning', 'Error', 'Critical', name='taskseverity'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('validations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('catalog_record_id', sa.String(), nullable=False),
    sa.Column('validator', sa.String(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_record_id'], ['catalog_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validations')
    op.drop_table('user_roles')
    op.drop_table('tasks')
    op.drop_index('ix_result_snapshots_lookup', table_name='result_snapshots')
    op.drop_table('result_snapshots')
    op.drop_index('ix_record_reviews_lookup', table_name='record_reviews')
    op.drop_table('record_reviews')
    op.drop_index('ix_marc_record_index_sector', table_name='marc_record_index')
    op.drop_table('marc_record_index')
    op.drop_table('comparisons')
    op.drop_table('authority_links')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_table('marc_sectors')
    op.drop_index('idx_catalog_records_updated_at', table_name='catalog_records')
    op.drop_index('idx_catalog_records_search_vector', table_name='catalog_records', postgresql_using='gin')
    op.drop_table('catalog_records')
    # ### end Alembic commands ###
