services:
  postgres:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_DB=marc
      - POSTGRES_USER=marcAdmin
      - POSTGRES_PASSWORD=marcAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marc-comparator
    ports:
      - '5432:5432'
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=replaceMe
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - marc-comparator
    ports:
      - "9200:9200"

  redis:
    image: redis:7-alpine
    networks:
      - marc-comparator
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: app/app.Containerfile
    depends_on:
      - postgres
      - elasticsearch
      - redis
    env_file:
      - config/app-docker.env
    volumes:
    - ./config/aleph.yaml:/app/config/aleph.yaml:ro
    networks:
      - marc-comparator
    ports:
      - "8000:8000"
    
  worker:
    build:
      context: .
      dockerfile: app/worker.Containerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - config/app-docker.env
    volumes:
    - ./config/aleph.yaml:/app/config/aleph.yaml:ro
    networks:
      - marc-comparator

volumes:
  postgres_data:

networks:
  marc-comparator: