apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marc-comparator.fullname" . }}-app
  labels:
    {{- include "marc-comparator.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "marc-comparator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "marc-comparator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: {{ include "marc-comparator.image" (dict "image" .Values.app.image "global" .Values.image) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "marc-comparator.fullname" . }}-config
            - secretRef:
                name: {{ include "marc-comparator.fullname" . }}-secret
          livenessProbe:
            httpGet:
              path: /system/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /system/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
