apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marc-comparator.fullname" . }}-cnpg-auth
  labels:
    {{- include "marc-comparator.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.owner | quote }}
  password: {{ .Values.secrets.postgresPassword | quote }}
