apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marc-comparator.fullname" . }}-secret
  labels:
    {{- include "marc-comparator.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  {{- if .Values.secrets.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
