apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marc-comparator.fullname" . }}-worker
  labels:
    {{- include "marc-comparator.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "marc-comparator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "marc-comparator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "marc-comparator.image" (dict "image" .Values.worker.image "global" .Values.image) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "marc-comparator.fullname" . }}-config
            - secretRef:
                name: {{ include "marc-comparator.fullname" . }}-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
