services:
  postgres:
    image: postgres:17.5-alpine
    container_name: marc-comparator-postgres
    environment:
      - POSTGRES_DB=marc
      - POSTGRES_USER=marcAdmin
      - POSTGRES_PASSWORD=marcAdmin
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - marc-comparator
    ports:
      - '5432:5432'
  
  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: marc-comparator-clickhouse
    volumes:
      - ./ch_data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - CLICKHOUSE_DB=marc
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    networks:
      - marc-comparator
    ports:
      - "8123:8123"

  redis:
    image: redis:7-alpine
    container_name: marc-comparator-redis
    networks:
      - marc-comparator
    ports:
      - "6379:6379"

  app:
    image: marc-comparator-app:${TAG:-local}
    container_name: marc-comparator-app
    depends_on:
      - postgres
      - clickhouse
      - redis
    env_file:
      - app.env
    networks:
      - marc-comparator
    ports:
      - "8000:8000"
    
  worker:
    image: marc-comparator-worker:${TAG:-local}
    container_name: marc-comparator-worker
    depends_on:
      - postgres
      - clickhouse
      - redis
    env_file:
      - app.env
    networks:
      - marc-comparator

  ollama:
    image: ollama/ollama:latest
    container_name: marc-comparator-llm
    networks:
      - marc-comparator
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama/models
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh:ro
    environment:
      - MODELS=qwen2.5vl:7b
    entrypoint: ["/ollama-entrypoint.sh"]
  
  client:
    image: marc-comparator-client:${TAG:-local}
    container_name: marc-comparator-client
    depends_on:
      - app
    networks:
      - marc-comparator
    ports:
      - "8080:80"
  
networks:
  marc-comparator:
    name: marc-comparator