services:
  postgres:
    image: pgduckdb/pgduckdb:17-main
    container_name: marc-comparator-postgres
    environment:
      - POSTGRES_DB=marc
      - POSTGRES_USER=marcAdmin
      - POSTGRES_PASSWORD=marcAdmin
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    command: >
      postgres
        -c shared_preload_libraries=pg_duckdb
    networks:
      - marc-comparator
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    container_name: marc-comparator-redis
    networks:
      - marc-comparator
    ports:
      - "6379:6379"

  app:
    image: marc-comparator-app:${TAG:-local}
    container_name: marc-comparator-app
    depends_on:
      - postgres
      - redis
    env_file:
      - app.env
    networks:
      - marc-comparator
    ports:
      - "8000:8000"

  worker:
    image: marc-comparator-worker:${TAG:-local}
    container_name: marc-comparator-worker
    depends_on:
      - postgres
      - redis
    env_file:
      - app.env
    networks:
      - marc-comparator

  beat:
    image: marc-comparator-worker:${TAG:-local}
    container_name: marc-comparator-beat
    depends_on:
      - redis
    env_file:
      - app.env
    command: ["celery", "-A", "adapters.tasks", "beat", "-S", "redbeat.RedBeatScheduler", "--loglevel=info"]
    networks:
      - marc-comparator

  ollama:
    image: ollama/ollama:latest
    container_name: marc-comparator-llm
    networks:
      - marc-comparator
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama/models
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh:ro
    environment:
      - MODELS=qwen2.5vl:7b
    entrypoint: ["/ollama-entrypoint.sh"]
  
  client:
    image: marc-comparator-client:${TAG:-local}
    container_name: marc-comparator-client
    depends_on:
      - app
    networks:
      - marc-comparator
    ports:
      - "8080:80"
  
networks:
  marc-comparator:
    name: marc-comparator